### CONFIGURATION GENERALE ###
spring.application.name=Rich Chat Server
server.port=8080
# propriété suivante à activer si l'application est lancée derrière un reverse proxy et dont le chemin d'accès n'est pas la racine du domaine
#server.forward-headers-strategy=FRAMEWORK
#profiles d'intérêt: development, sample-data
spring.profiles.active=development, sample-data

spring.web.resources.static-locations=file:/var/www/rich-chat

### CONFIGURATION POUR LE DEVELOPPEMENT ###
# propriétés suivantes à activer en production
# spring.devtools.add-properties=false
# spring.devtools.restart.enabled=false
# En dev, exclusion des fichier static pour éviter le redémarrage auto
spring.devtools.restart.exclude=static/**,public/**,developmentEnv/**

### CONFIGURATION ACCES DB ###
spring.data.mongodb.database=richchat-db
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.host=127.0.0.1
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=cocomposer-svc
#spring.data.mongodb.password=9PE4UrfCAntq5kMT

### CONFIGURATIONS DE LA SECURITE ###
# Sécurité CORS et CSRF
app.security.cors-dev=true
# METTRE SUR FALSE LE CSRF POUR LE DEV !
app.security.csrf=false 
app.security.local-admin=rvenant
# Gestion de cookies de session
server.servlet.session.cookie.name=RICHCHATSESSIONID
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.domain=localhost
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.max-age=1h

# Gestion des sessions
server.servlet.session.timeout=1h

### CONFIGURATION DU COMPORTEMENT DU SERVEUR HTTP ###
# Configuration du cache de ressources coté client
# n'importe quel client peut stocker en cache une réponse
spring.web.resources.cache.cachecontrol.cache-public=true
# une réponse peut être cachée au plus 1h (3600 sec)
spring.web.resources.cache.cachecontrol.max-age=3600
# quand une rép. est "vieille", elle doit être revalidée
spring.web.resources.cache.cachecontrol.must-revalidate=true

### CONFIGURATION DE LA JOURNALISATION ###
# Configuration des journaux
logging.level.richChatServer=INFO
#logging.level.richChatServer.controllers=DEBUG
#logging.level.richChatServer.model=DEBUG
#logging.level.richChatServer.services=DEBUG
#logging.level.richChatServer.security=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.mongodb.driver.protocol=DEBUG
#logging.level.org.springframework.messaging=DEBUG